SELECT * FROM EMPLOYEES;

-- WE WANT TO PRINT EMPLOYEES FULL NAME WITH MANAGERS NAME
SELECT E1.FIRST_NAME, E1.LAST_NAME, E2.FIRST_NAME
FROM EMPLOYEES E1 JOIN EMPLOYEES E2
ON E1.EMPLOYEE_ID = E2.EMPLOYEE_ID;