SELECT * FROM EMPLOYEES;

SELECT * FROM DEPARTMENTS;

SELECT REGION_NAME FROM REGIONS;
-- DISTINCT WILL GIVE YOU NO DUPLICATES
SELECT FIRST_NAME FROM EMPLOYEES;
SELECT DISTINCT FIRST_NAME FROM EMPLOYEES;
SELECT DISTINCT JOB_ID FROM EMPLOYEES;
SELECT DISTINCT  COUNTRY_ID FROM  LOCATIONS;
SELECT DISTINCT JOB_ID FROM JOBS;
----------------WHERE-----------------------------------

SELECT  FIRST_NAME , LAST_NAME, SALARY FROM EMPLOYEES
WHERE FIRST_NAME = 'David';

SELECT FIRST_NAME, SALARY FROM EMPLOYEES
WHERE  FIRST_NAME = 'Jack';

SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES
WHERE  FIRST_NAME = 'David';

SELECT FIRST_NAME , LAST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY < 6000;

SELECT FIRST_NAME , LAST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY <= 6000;

SELECT FIRST_NAME , LAST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY >= 6000 AND SALARY <=8000;  -- <= INCLUDE

SELECT FIRST_NAME , LAST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY BETWEEN 6000 AND 8000; -- SAME INCLUDE


SELECT FIRST_NAME , LAST_NAME, DEPARTMENT_ID, SALARY FROM EMPLOYEES
WHERE SALARY > 6000 AND  DEPARTMENT_ID = 80;

SELECT FIRST_NAME , LAST_NAME, DEPARTMENT_ID, SALARY FROM EMPLOYEES
WHERE SALARY > 6000 AND SALARY <=7000 AND DEPARTMENT_ID = 80;

SELECT  * FROM EMPLOYEES
WHERE JOB_ID = 'IT_PROG';

SELECT  * FROM EMPLOYEES
WHERE JOB_ID = 'SA_REP' OR JOB_ID = 'IT_PROG';

-------------------IN---CLOUSE-----------------------------------

SELECT * FROM  EMPLOYEES
WHERE JOB_ID IN ('IT_PROG','ST_MAN');

SELECT  * FROM EMPLOYEES
WHERE JOB_ID IN ('SA_REP');

SELECT CITY,COUNTRY_ID FROM LOCATIONS
WHERE  COUNTRY_ID IN ('US','UK','IT');

SELECT  POSTAL_CODE , CITY , COUNTRY_ID FROM LOCATIONS
WHERE COUNTRY_ID NOT IN ('IT','US');

SELECT * FROM EMPLOYEES
WHERE EMPLOYEE_ID IN (122,133,110);

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NULL;

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL;

--------ORDER--BY----------

SELECT * FROM EMPLOYEES
ORDER BY SALARY; -- SAME ORDER SORT
SELECT * FROM EMPLOYEES
ORDER BY SALARY ASC ; --- SAME ORDER SORT
SELECT * FROM EMPLOYEES
ORDER BY 8 ASC ; -- 8 IS NUMBER OF THE COLUM

SELECT * FROM EMPLOYEES
ORDER BY SALARY DESC ;

SELECT EMPLOYEE_ID, FIRST_NAME,LAST_NAME FROM EMPLOYEES
ORDER BY 3 ASC ; -- WILL SORT COLUM

SELECT * FROM EMPLOYEES
ORDER BY 9 ASC ; -- COMMISSION_PCT --> IN ORDER

SELECT  * FROM  EMPLOYEES
WHERE EMPLOYEE_ID < 120
ORDER BY FIRST_NAME; -- WILL SORT FIRST NAME

SELECT  * FROM  EMPLOYEES
WHERE EMPLOYEE_ID < 120
ORDER BY 2; -- WILL SORT FIRST NAME

SELECT * FROM EMPLOYEES
ORDER BY FIRST_NAME ASC,LAST_NAME DESC;

SELECT  * FROM EMPLOYEES
ORDER BY SALARY ASC;

SELECT  * FROM EMPLOYEES
ORDER BY SALARY DESC ;











































