SELECT * FROM EMPLOYEES;
 -- WILL DO RANGE INCLUDE LOWER BUT  NOT  HIGHER
SELECT  FIRST_NAME , SALARY FROM EMPLOYEES
WHERE SALARY > 7000 AND SALARY < 10000;

-- "BETWEEN" ->  WILL DO RANGE INCLUDE LOWER AND HIGHER

SELECT  FIRST_NAME , SALARY FROM EMPLOYEES
WHERE SALARY BETWEEN 7000 AND  10000;

SELECT FIRST_NAME,LAST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY > 7000 AND  DEPARTMENT_ID = 80;

SELECT * FROM EMPLOYEES
WHERE JOB_ID = 'IT_PROG' OR JOB_ID = 'SA_REP';

