SELECT  * FROM EMPLOYEES;

SELECT FIRST_NAME,LAST_NAME,SALARY FROM EMPLOYEES
WHERE FIRST_NAME = 'David';

SELECT  FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES
WHERE FIRST_NAME = 'David' AND LAST_NAME = 'Lee';

SELECT * FROM  EMPLOYEES
WHERE SALARY >6000;

SELECT  * FROM EMPLOYEES
WHERE  SALARY <= 6000;

SELECT  * FROM EMPLOYEES
WHERE  SALARY = 6000 OR SALARY < 6000;


