SELECT * FROM EMPLOYEES;

/*
 IN CLOUSE
 */

SELECT * FROM EMPLOYEES
WHERE JOB_ID = 'IT_PROG' OR JOB_ID = 'SA_REP' OR JOB_ID = 'ST_MAN' OR JOB_ID = 'MK_REP';


SELECT  * FROM EMPLOYEES
WHERE JOB_ID IN ('IT_PROG','SA_REP','ST_MAN','MK_REP'); -- SAME CODE  BUT SHORT

SELECT  CITY , COUNTRY_ID FROM LOCATIONS
WHERE COUNTRY_ID IN ('IT','US','UK');

--DISPLAY POSTAL CODE CITY WHERE COUNTRY_ID IS NOT IT , US
SELECT POSTAL_CODE, CITY FROM LOCATIONS
WHERE COUNTRY_ID NOT IN ('IT','US');

-- DISPLAY ALL INFORMATION WHERE EMPLOYEES_ID IS 134 , 123, 145,146
SELECT * FROM EMPLOYEES
WHERE EMPLOYEE_ID IN (134,123,146,145);

-- DISPLAY  ALL INFORMATION FOR EMPLOYEES WHOSE DEPARTMENT ID IS ->  NULL (NOT AVAILABLE, IS EMPTY)
SELECT * FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NULL;




