SELECT * FROM EMPLOYEES;
-- WE CREATE VIRTUAL TABLE SDET
CREATE VIEW  SDET AS
SELECT  SUBSTR(FIRST_NAME,0,1) || SUBSTR(LAST_NAME,0,1)  AS INITIALS,
       FIRST_NAME || 'MAKES $' || SALARY AS "EMPLOYEES_SALARY"
            FROM EMPLOYEES; -- RUN SDET,  AFTER YOU DROP
SELECT * FROM SDET;
SELECT INITIALS FROM SDET;
-- REMOVE TABLE SDET
DROP  VIEW SDET; -- IF YOU WANT RUN AGAIN,  GO BACK AND RUN "CREATE VIEW SDET AS" OVER AGAIN
SELECT * FROM SDET;
