SELECT * FROM EMPLOYEES;

----------------CREATE TABLE-----------------
CREATE  TABLE SCRUMTEAM (
    EMP_ID NUMBER PRIMARY KEY, --  NULL IS  NOT ALLOWED NO DUPLICATE
    FIRST_NAME VARCHAR(30) NOT NULL, -- CAN NOT BE NULL
    JOB_TITLE VARCHAR(20) NOT NULL,
    AGE INTEGER, -- CAN HAVE DUPLICATES AND NULL
    SALARY INTEGER-- CAN HAVE DUPLICATES AND NULL
);
SELECT * FROM SCRUMTEAM;

--------------PUTTING SOME DATA-----------------
INSERT INTO SCRUMTEAM (EMP_ID, FIRST_NAME, JOB_TITLE, AGE, SALARY)
VALUES (2,'Tom','Dev', 55,32000);
SELECT * FROM SCRUMTEAM;

INSERT INTO SCRUMTEAM (EMP_ID, FIRST_NAME, JOB_TITLE, AGE, SALARY)
VALUES (2,'Lilu','Dev', 55,32000);
SELECT * FROM SCRUMTEAM;

INSERT INTO SCRUMTEAM (EMP_ID, FIRST_NAME, JOB_TITLE, AGE, SALARY)
VALUES (3,'Bobi','SCRUM', 52,52000);
SELECT * FROM SCRUMTEAM;

-- HOW TO SAVE---------------
COMMIT ;


--HOW TO DELETE-------------
SELECT * FROM SCRUMTEAM;
DELETE FROM SCRUMTEAM
WHERE FIRST_NAME = 'Sam';

DELETE FROM SCRUMTEAM
WHERE FIRST_NAME = 'Bob';

DELETE FROM SCRUMTEAM
WHERE FIRST_NAME = 'Mark';

--ALER TABLE ------------
----ADD COLUM
----DROP COLUM
----RENAME COLUM
----RENAME TO
ALTER TABLE SCRUMTEAM
ADD  GENDER VARCHAR(10);
SELECT * FROM SCRUMTEAM;
---ADD VALUES TO GENDER
UPDATE SCRUMTEAM
SET  GENDER = 'Male'
WHERE FIRST_NAME = 'Jeck';
SELECT * FROM SCRUMTEAM;

--------------RENAME COLUM-------------
ALTER TABLE  SCRUMTEAM
RENAME COLUMN SALARY TO  ANNUAL_SALARY;
SELECT * FROM SCRUMTEAM;

ALTER TABLE SCRUMTEAM
RENAME TO AGAILTEAM;
SELECT * FROM SCRUMTEAM; --- WE DELETED
SELECT * FROM AGAILTEAM;

--TRUNCATE --> DELETE DATA FROM TABLE
--DROP ---> DELETE WHOLE TABLE
--COMMIT ---> SAVE GANGES

TRUNCATE TABLE AGAILTEAM; -- DELETE  DATE FROM TABLE
SELECT * FROM AGAILTEAM;

DROP TABLE  AGAILTEAM; -- DELETE WHOLE TABLE
SELECT * FROM AGAILTEAM;
SELECT * FROM SCRUMTEAM;

COMMIT;

---ONCE YOU DROP TABLE YOU HAVE TO GREAT EVERYTHING START OVER


















