SELECT * FROM EMPLOYEES;

SELECT MAX(SALARY) FROM EMPLOYEES;

SELECT * FROM EMPLOYEES
WHERE SALARY = 24000;

-- WE DYNAMICALLY GET THE HIGHEST SALARY
SELECT * FROM EMPLOYEES
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES);
-----------------------------------------------------
--DISPLAY SECOND HIGHEST SALARY
SELECT MAX(SALARY) FROM EMPLOYEES
WHERE  SALARY <24000;

--DYNAMIC OPTION FOR HIGHEST SECOND SALARY
SELECT MAX(SALARY) FROM EMPLOYEES
WHERE  SALARY < (SELECT MAX(SALARY) FROM EMPLOYEES);
-------------------------------------------------------
---GET
SELECT * FROM  EMPLOYEES
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES
                WHERE  SALARY < (SELECT MAX(SALARY) FROM EMPLOYEES));


-- Display all the employees who are making above the average salary
select ROUND(AVG(SALARY)) from EMPLOYEES; -- 6462

select * from EMPLOYEES
where SALARY > 6462;

-- make dynamic
select * from EMPLOYEES
where SALARY > (select ROUND(AVG(SALARY)) from EMPLOYEES);





