SELECT * FROM EMPLOYEES;

SELECT COUNT(*) FROM DEPARTMENTS;-- SINGLE ROW
SELECT COUNT(LOCATION_ID) FROM DEPARTMENTS;--DIVE YOU JUST SINGLE ROW
SELECT LOCATION_ID FROM DEPARTMENTS;--GIVE YOU TABLE WITH MANY ROWS
SELECT COUNT(DISTINCT LOCATION_ID) FROM DEPARTMENTS; -- NO DUPLICATES
SELECT LOCATION_ID, COUNT(*) AS "TOTAL COUNT" FROM DEPARTMENTS
GROUP BY LOCATION_ID;

--GET HOW MANY LOCATIONS WE HAVE FROM EACH COUNTRY_ID

SELECT COUNTRY_ID, COUNT(*) FROM LOCATIONS
GROUP BY COUNTRY_ID
ORDER BY 1 ASC;
-- HOW MANY COUNTRIES WE HAVE FROM EACH REGION
SELECT * FROM COUNTRIES;

SELECT REGION_ID, COUNT (*) FROM COUNTRIES
GROUP BY REGION_ID
ORDER BY REGION_ID








