SELECT * FROM EMPLOYEES;

SELECT * FROM JOBS
--Display all jobs witch title is 'President','Sales Manager','Programmer'
WHERE JOB_TITLE  IN ('President','Sales Manager');
--Display all jobs witch title is not 'President','Sales Manager','Programmer'

SELECT * FROM JOBS
WHERE JOB_TITLE  not in  ('President','Sales Manager','Programmer');

-- DISPLAY ALL DEPARTMENT THAT DOES NOT HAVE MANAGER_ID IN DEPARTMENT TABLE
select * from DEPARTMENTS
where  MANAGER_ID is  null;
--DISPLAY ALL INFORMATION WHERE COUNTRY ID IS  US OR GB FROM LOCATION TABLE
SELECT  * FROM LOCATIONS
WHERE  COUNTRY_ID IN ('US','GB');
--DISPLAY ALL INFORMATION WHERE COUNTRY ID IS NOT US OR GB FROM LOCATION TABLE
SELECT  * FROM LOCATIONS
WHERE  COUNTRY_ID NOT IN ('US','GB');

SELECT  * FROM COUNTRIES
WHERE REGION_ID = 10 AND  COUNTRY_NAME = 'Belgium';

SELECT  * FROM COUNTRIES
WHERE REGION_ID = 10 and  COUNTRY_NAME not in 'Belgium';
SELECT  * FROM EMPLOYEES
WHERE  DEPARTMENT_ID NOT IN (90,60,130,120,100);

SELECT FIRST_NAME , LAST_NAME ,DEPARTMENT_ID FROM EMPLOYEES
WHERE DEPARTMENT_ID NOT IN (90,60,130,120,100);


-------------------LIKE--------------------
------B%--STARTS----%B--ENDS-----
-------STARTS----------------
SELECT  * FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'B%';

SELECT  FIRST_NAME FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'B%';
---------ENDS-------------
SELECT  FIRST_NAME FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%a';
-------CONTAINS--5--CHARACTERS--
SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE  'B____';
----MIDDLE--CHAR--A----
SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE '__a__';

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%a%';
-----5--LONG--NAME----
SELECT FIRST_NAME FROM EMPLOYEES
WHERE FIRST_NAME LIKE '_____';

SELECT FIRST_NAME FROM EMPLOYEES
WHERE FIRST_NAME LIKE '_a___';

SELECT FIRST_NAME FROM EMPLOYEES
WHERE FIRST_NAME LIKE '_a%';


---ENDS--WITH--l----
SELECT  LAST_NAME FROM  EMPLOYEES
WHERE FIRST_NAME LIKE '%l';

SELECT  FIRST_NAME ,LAST_NAME FROM  EMPLOYEES
WHERE FIRST_NAME LIKE '%l';

---ENDS--WITH--MANAGER--

SELECT * FROM JOBS
WHERE JOB_TITLE LIKE '%Manager';

--------COUNT------------
SELECT COUNT (FIRST_NAME) FROM EMPLOYEES; --107
SELECT  FIRST_NAME FROM EMPLOYEES;

SELECT COUNT (MANAGER_ID) FROM EMPLOYEES; --106 NO NULL
SELECT MANAGER_ID FROM EMPLOYEES; --107 WITH NULL

SELECT COUNT (SALARY) FROM EMPLOYEES;
SELECT  SALARY FROM EMPLOYEES;
---NO---DUPLICATES---
SELECT DISTINCT FIRST_NAME FROM EMPLOYEES;
SELECT COUNT (DISTINCT FIRST_NAME) FROM EMPLOYEES; --92

--HOW  MANY EMPLOYEES WORK AS 'IT_PROG' OR 'SA_REP'
SELECT COUNT(*) FROM EMPLOYEES
WHERE JOB_ID IN ('IT_PROG','SA_REP');


----MIN----
SELECT MIN(SALARY) FROM EMPLOYEES;
----MAX----
SELECT MAX(SALARY) FROM EMPLOYEES;
----AVERAGE-----
SELECT AVG(SALARY) FROM EMPLOYEES;
SELECT ROUND (AVG(SALARY),4) FROM EMPLOYEES; -- WILL GIVE YOU LAST 4 DIGITS
SELECT ROUND (AVG(SALARY),2) FROM EMPLOYEES; -- WILL GIVE YOU LAST 2 DIGITS
---TOTAL---
SELECT SUM(SALARY) FROM EMPLOYEES;
--AVERAGE SALARY FROM IT_PROG
SELECT AVG(SALARY) FROM EMPLOYEES
WHERE JOB_ID = 'IT_PROG';
-----MAX---FROM---SA_REP--
SELECT MAX(SALARY) FROM EMPLOYEES
WHERE JOB_ID = 'SA_REP';

-----GROUP--BY---WILL--GIVE --YOU---UNIQUE---SAME---AS---DISTINCT
SELECT DISTINCT JOB_ID FROM EMPLOYEES;
SELECT JOB_ID FROM EMPLOYEES
GROUP BY JOB_ID; ---SAME AS DISTINCT


SELECT JOB_ID, AVG (SALARY), MAX (SALARY),MIN(SALARY)FROM EMPLOYEES
group by JOB_ID;

SELECT JOB_ID FROM EMPLOYEES
GROUP BY JOB_ID;


SELECT   ROUND (AVG (SALARY),2)  FROM EMPLOYEES;

SELECT DEPARTMENT_ID FROM EMPLOYEES;
SELECT ROUND (AVG (SALARY),2), MIN (SALARY), MAX (SALARY), SUM (SALARY) ,COUNT (*)  FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;
-- JOB_ID SALARY MORE THAN 5000K

SELECT DEPARTMENT_ID, ROUND(AVG(SALARY),2) FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, MAX(SALARY), MIN(SALARY), ROUND (AVG(SALARY),2), SUM(SALARY) FROM EMPLOYEES
GROUP BY DEPARTMENT_ID


-- JOB_ID SALARY MORE THAN 5000K

SELECT JOB_ID,  AVG (SALARY) FROM  EMPLOYEES
WHERE SALARY > 5000
GROUP BY JOB_ID;


SELECT JOB_ID, AVG (SALARY) FROM EMPLOYEES
GROUP BY JOB_ID
HAVING AVG(SALARY) > 5000;

-- INTERVIEW QUESTION
    -- DISPLAY DUPLICATES NAMES IN EMPLOYEES
SELECT FIRST_NAME, COUNT (*)  FROM EMPLOYEES
GROUP BY FIRST_NAME
HAVING COUNT(*)> 1;








---









































































